title = "Blogzam"

baseurl = "https://www.ilzamafif.github.io/blogzam"

MetaDataFormat = "yaml"

themesDir = "themes"

theme = "kendi"

description = ""

languageCode = "id-ID"

disqusShortname = "ilzamafif" 

googleAnalytics = "UA-171646750-1" 

[Author] 
  name = "Ilzam Afif"

