baseURL = "https://blogzam.js.org/"
languageCode = "en-us"
title = "blogzam"
theme = "hugo-theme-yinyang"
DefaultContentLanguage = "cn"

[author]
  name = "ilzam afif"
  homepage = "https://twitter.com/ilzam27_"


[params]
mainSections = ["post"]
headTitle = "blogzam"
# Google analytics code - remove if you do not have/want Google Analytics - needs JavaScript
googleAnalytics = "UA-171646750-1"
[[params.socials]]
name = "About Me"
link = "https://instagram.com/ilzamafif"
[[params.socials]]
name = "Github"
link = "https://github.com/ilzamafif"
postHeaderContent = ""
postFooterContent = "<br/><br/><p>Subscribe to：<a target='_blank' href='https://mailchi.mp/a1a0d59e7a19/joway'>Joway's Blog</a></p>"
# extraCSSFiles = ["css/foo.css", "css/bar.css"]
extraCSSFiles = []