baseurl = "https://blogzam.js.org/"
title = "blogzam"
theme = "yinyang"

# disqus & googleAnalytics
DisqusShortname = ""
googleAnalytics = "UA-175167654-1"


# Biodata Author
[author]
#site author
    name = "ilzam afif"
    homepage = "https://twitter.com/ilzam27_"
    bio = ""
# Untuk deskripsi tag meta di homepag
# description = "blogzam merupakan tempat belajar pemogramman berbahasa indonesia yang memiliki beberapa fitur yaitu course online, diskusi online, dan ujian online."

# keyword = "pemogramman web, belajar membuat website, web programming, pemogramman, membangun website, belajar ngoding, koding, tutorial bahasa indonesia"


[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]


[menu]
  [[menu.main]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/ilzamafif"
    wight = 1