baseURL = "http://blogzam.js.org/"
languageCode = "en-us"
title = "ayamjago"


# Agar front-matter pakai format YAML
MetaDataFormat = "yaml"

# untuk apply temanya
themesDir = "themes"
theme = "ayamjago"

# Shortname disqus, silahkan sesuaikan
DisqusShortname = ""

# Untuk Google Analytic, silahkan sesuikan
googleAnalytics = "UA-80517197-1" 

# Untuk deskripsi tag meta di homepage
description = ""

# Biodata Author
[author]
    name = "Ilzam Afif"
    homepage = "https://github.com/ilzamafif/"
    bio = "praja muda karana"
    image = ""
