title = "Blogzam"

baseurl = "/"

MetaDataFormat = "yaml"

themesDir = "themes"

theme = "kendi"

description = ""

languageCode = "id-ID"

disqusShortname = "ilzamafif" 

googleAnalytics = "UA-171646750-1" 

[Author] 
  name = "Ilzam Afif"


[Permalinks]
    post = "/:filename/"